#!/usr/bin/env python3
"""Generate a system's `.claude/settings.json` from the federation floor.

Per ADR-0034: `.claude/settings.json` is federation-pushed substrate. It is
GENERATED (do-not-hand-edit) from two inputs:

  1. the shared FLOOR — `standard-settings.json` at the federation root (the
     single source of the permission/hook baseline every Architect gets), and
  2. the system's OWN `settings_extras` (a block in its `session.config.json`),
     which may ADD allow/deny entries and extra SessionStart hooks — never
     subtract from the floor.

The floor + extras are composed here; the result is written verbatim into the
target's `.claude/settings.json`. Because it is rebuilt from known inputs, a
push never has to preserve unknown content — it overwrites, and a system's own
additions survive because they live in `settings_extras` (tracked in that
system's git), not scraped from the file being overwritten. Genuinely
per-machine overrides live in the gitignored `settings.local.json`, which this
generator never touches.

No judgment — pure transcription of floor + declared extras (P15).

CLI (federation's own copy):
  python3 curate/gen_settings.py            # (re)write the federation's .claude/settings.json
  python3 curate/gen_settings.py --check    # fail if that file is stale vs floor+extras

Library (used by curate/push-substrate.py to render each target):
  from gen_settings import render
  text = render(target_config_dict)
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

FED_ROOT = Path(__file__).resolve().parent.parent
FLOOR_PATH = FED_ROOT / "standard-settings.json"

GENERATED_BANNER = (
    "GENERATED by curate/gen_settings.py from standard-settings.json (the "
    "federation floor) + this system's session.config.json `settings_extras` "
    "(ADR-0034). DO NOT hand-edit — the next federation push overwrites it. To "
    "change the shared floor: edit standard-settings.json in the federation. To "
    "add a local permission/hook: add it to settings_extras in session.config.json. "
    "For a genuinely per-machine override: use the gitignored settings.local.json."
)


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


# The floor writes every hook command as `python3 "$CLAUDE_PROJECT_DIR/<script>" …`,
# which assumes the harness sits at the Architect's launch cwd. That holds for every
# kit member and fails for a RESIDENT-RUNTIME member, where the repo root belongs to
# another agent and the Architect launches from a separate pad (no CLAUDE.md may sit
# anywhere in that agent's load path, so the Architect's launch dir is a sibling, not a
# subdirectory). There `$CLAUDE_PROJECT_DIR` is the pad and the harness is elsewhere —
# a verbatim floor push produces dead hooks, and a member left to hand-maintain its
# copy drifts on every floor movement.
HARNESS_ANCHOR = '"$CLAUDE_PROJECT_DIR/'


def _normalize_harness_dir(raw) -> str:
    """`harness_dir` config value -> a clean relative prefix, or "" for no rewrite.

    Refuses an absolute path or one containing a double quote: the value is spliced
    into a shell command inside a JSON string, so both would produce a silently
    broken settings file. A bad declaration fails loud rather than shipping dead
    hooks to a member (the failure mode this whole key exists to end)."""
    if not isinstance(raw, str):
        return ""
    hd = raw.strip().rstrip("/")
    if hd in ("", "."):
        return ""
    if hd.startswith("/") or '"' in hd:
        raise ValueError(
            f"harness_dir must be a relative path with no quote character; got {raw!r}"
        )
    return hd


# `pad_dir` (repo-root -> the Architect's launch pad) and `harness_dir`
# (pad -> the harness) describe one relationship from opposite ends, so deriving one
# from the other is tempting. It is not possible from the config alone: inverting
# `pad_dir: "../architect"` requires the repo's own DIRECTORY NAME, which no config
# records. A derivation that guessed it would emit dead hooks — the precise failure
# `harness_dir` exists to end — so both are declared, and this note is here so the
# redundancy reads as considered rather than sloppy.


def _retarget_hook_commands(hooks: dict, harness_dir: str) -> None:
    """Rewrite FLOOR hook commands in place to reach the harness at `harness_dir`.

    Only the `command` fields are touched — the floor's `//` authoring notes keep
    their generic wording, and `permissions` carries no such path. Applied to the
    floor ONLY, before extras are merged: `settings_extras` are authored by the
    member with full knowledge of its own layout, so they stay verbatim."""
    for groups in (hooks or {}).values():
        for group in groups or []:
            for hook in group.get("hooks") or []:
                cmd = hook.get("command")
                if isinstance(cmd, str) and HARNESS_ANCHOR in cmd:
                    hook["command"] = cmd.replace(
                        HARNESS_ANCHOR, f'{HARNESS_ANCHOR}{harness_dir}/'
                    )


def generate(floor: dict, config: dict | None) -> dict:
    """Pure: floor dict + a system config dict -> the settings dict to write.

    allow/deny extras are appended after the floor entries (deduped, order
    preserved); extra SessionStart hooks are appended after the floor's. The
    floor's authoring-only `//` comment is dropped in favour of the generated
    banner; the other `//hooks`/`//pretooluse`/`//git-c` notes are kept.

    A declared `harness_dir` retargets the floor's hook commands at a harness that
    is not at the launch cwd (the resident-runtime layout). Default "." leaves the
    render byte-identical to the pre-harness_dir output for every other member."""
    cfg = config or {}
    extras = (cfg.get("settings_extras")) or {}
    body = json.loads(json.dumps(floor))  # deep copy
    body.pop("//", None)

    harness_dir = _normalize_harness_dir(cfg.get("harness_dir"))
    if harness_dir:
        _retarget_hook_commands(body.get("hooks") or {}, harness_dir)

    result: dict = {"//generated": GENERATED_BANNER}
    result.update(body)

    perms = result.setdefault("permissions", {})
    for key in ("allow", "deny"):
        merged = list(perms.get(key, []))
        for entry in (extras.get(key) or []):
            if entry not in merged:
                merged.append(entry)
        perms[key] = merged

    # Extra hooks, keyed by event (SessionStart, PreToolUse, …), appended after
    # the floor's own hooks for that event. General enough to carry a system's
    # own PreToolUse guard (e.g. a project-side close guard) or extra status
    # probes — the additive-substrate case (ADR-0023 / ADR-0034).
    for event, entries in (extras.get("hooks") or {}).items():
        bucket = result.setdefault("hooks", {}).setdefault(event, [])
        bucket.extend(entries or [])

    # Any OTHER top-level key a member declares (`model`, `env`, `statusLine`, …) is
    # carried through. Until this existed, `settings_extras` silently dropped anything
    # that was not allow/deny/hooks — so a member could not pin its Architect's model
    # in-repo at all, and the omission looked exactly like a setting that had been
    # applied. ADD-only: a key the floor already defines is NOT overridable here, since
    # the floor is a floor (ADR-0023 no-subtraction) — a member that needs a different
    # `hooks`/`permissions` shape changes the floor, not its own copy.
    for key, value in extras.items():
        if key in ("allow", "deny", "hooks") or key in result:
            continue
        result[key] = value

    return result


def render(config: dict | None) -> str:
    """Rendered settings.json text for a system with the given config."""
    floor = _load(FLOOR_PATH)
    return json.dumps(generate(floor, config), indent=2, ensure_ascii=False) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate .claude/settings.json from the floor.")
    ap.add_argument("--check", action="store_true",
                    help="fail (exit 1) if the target file is stale vs floor+extras")
    ap.add_argument("--config", default=str(FED_ROOT / "session.config.json"),
                    help="session.config.json to read settings_extras from")
    ap.add_argument("--out", default=str(FED_ROOT / ".claude" / "settings.json"),
                    help="settings.json to write / check")
    args = ap.parse_args()

    config_path = Path(args.config)
    if not config_path.exists():
        # WI-0076. A MISSING config used to become `{}`, which renders the bare floor —
        # and the bare floor is IDENTICAL for every target, because everything that makes
        # a member's settings its own lives in `settings_extras`. That is exactly the
        # signature of an earlier event: several members' settings were
        # rewritten in the same minute, byte-identical, each missing its own enrollment
        # hook. Reproduced here — `render({})` for two different members returns the same
        # bytes, and it carries literal em-dashes, matching the odd copy's
        # serialization.
        #
        # `push-substrate` never had this hole: `settings_target()` returns None for a
        # repo with no `session.config.json`, on the stated rule that "a settings push
        # requires a declared config", and `_assert_extras_survived` refuses a shrinking
        # render. But BOTH of those guards live in push-substrate, while this script takes
        # arbitrary `--config` and `--out` and had neither. So the one write point with no
        # protection was the one a human drives by hand.
        #
        # Refusing rather than warning, for push-substrate's reason: a floor-only render
        # is never a legitimate output for a member — no member benefits from receiving
        # one — so emitting it and reporting the fact would still ship the harm.
        print(f"gen_settings: REFUSING — no config at {config_path}.\n"
              f"              A missing config renders the BARE FLOOR, which is identical "
              f"for every target: everything that makes a member's settings its own lives "
              f"in `settings_extras`. Writing that over a member silently deletes its own "
              f"hooks (WI-0076).\n"
              f"              Pass --config <that repo's session.config.json>, or use "
              f"`push-substrate.py`, which gates this case and asserts the declared hooks "
              f"survived. Nothing was written.", file=sys.stderr)
        sys.exit(2)
    config = _load(config_path)
    text = render(config)
    out = Path(args.out)

    if args.check:
        current = out.read_text(encoding="utf-8") if out.exists() else ""
        if current != text:
            print(f"STALE: {out} differs from standard-settings.json + extras — "
                  f"run `python3 curate/gen_settings.py`.")
            sys.exit(1)
        print(f"{out} in sync with the floor + extras.")
        return

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    extras = (config.get("settings_extras") or {})
    n_allow = len(extras.get("allow") or [])
    n_hooks = sum(len(v or []) for v in (extras.get("hooks") or {}).values())
    print(f"wrote {out} (floor + {n_allow} extra allow, {n_hooks} extra hook group(s))")


if __name__ == "__main__":
    main()
